from . import salon_service
from . import salon_staff
from . import salon_branch
from . import salon_room
from . import salon_appointment
from . import salon_package
from . import salon_membership
from . import salon_commission
from . import salon_review
from . import res_partner
from . import product_template
from . import res_config_settings
from . import salon_customer_history
from . import salon_service_step
from . import salon_staff_tip
from . import pos_order
