from . import salon_service_category
from . import salon_service
from . import hr_job
from . import salon_staff
from . import salon_room
from . import salon_block_type
from . import salon_block
from . import salon_appointment
from . import salon_package
from . import salon_membership
from . import salon_commission
from . import salon_review
from . import res_partner
from . import base_partner_merge
from . import product_template
from . import res_company
from . import res_config_settings
from . import salon_customer_history
from . import salon_customer_note
from . import salon_service_step
from . import salon_staff_tip
from . import pos_order
from . import pos_config
from . import report_sale_details
