# -*- coding: utf-8 -*-
from odoo import api, models
import datetime

class ReportSalonStaffPerformance(models.AbstractModel):
    _name = 'report.salon_spa_scheduler.report_salon_staff_performance_temp'
    _description = 'Salon Employee Performance Report Data Source'

    @api.model
    def _get_report_values(self, docids, data=None):
        date_from = data.get('date_from')
        date_to = data.get('date_to')
        staff_ids = data.get('staff_ids') or []
        branch_ids = data.get('branch_ids') or []

        staff_domain = []
        if staff_ids:
            staff_domain.append(('id', 'in', staff_ids))
        if branch_ids:
            appts_in_branch = self.env['salon.appointment'].sudo().search([('branch_id', 'in', branch_ids)])
            stf_in_branch = appts_in_branch.mapped('staff_id.id') + appts_in_branch.mapped('step_ids.staff_id.id')
            staff_domain.append(('id', 'in', list(set(stf_in_branch))))
        
        staff_records = self.env['salon.staff'].sudo().search(staff_domain, order='name asc')

        staff_performance = []
        grand_total_revenue = 0.0
        grand_total_tips = 0.0
        grand_total_commissions = 0.0
        grand_total_done = 0
        total_ratings_sum = 0.0
        total_ratings_count = 0

        for staff in staff_records:
            # 1. Appointments where staff is primary OR step staff
            appt_domain = [
                ('start_datetime', '>=', date_from),
                ('start_datetime', '<=', f"{date_to} 23:59:59"),
                '|', ('staff_id', '=', staff.id), ('step_ids.staff_id', '=', staff.id)
            ]
            if branch_ids:
                appt_domain.append(('branch_id', 'in', branch_ids))
                
            appts = self.env['salon.appointment'].sudo().search(appt_domain, order='start_datetime asc')

            total_appts = len(appts)
            done_appts = 0
            cancel_appts = 0
            active_appts = 0
            staff_revenue = 0.0
            services_log = []

            for appt in appts:
                if appt.state == 'done':
                    done_appts += 1
                elif appt.state == 'cancel':
                    cancel_appts += 1
                else:
                    active_appts += 1

                # Calculate revenue generated by THIS staff member on this appointment
                appt_rev = 0.0
                if appt.staff_id.id == staff.id:
                    appt_rev += appt.service_id.list_price
                    for line in appt.line_ids:
                        appt_rev += line.price_unit
                else:
                    # Check step lines if not primary staff
                    total_step_dur = sum(s.duration_minutes for s in appt.step_ids) or 1
                    for step in appt.step_ids:
                        if step.staff_id.id == staff.id:
                            tot_p = appt.service_id.list_price + sum(line.price_unit for line in appt.line_ids)
                            appt_rev += (step.duration_minutes / total_step_dur) * tot_p

                if appt.state == 'done':
                    staff_revenue += appt_rev

                services_log.append({
                    'appt_name': appt.name,
                    'customer': appt.partner_id.name or 'Walk-in',
                    'service': appt.service_id.name,
                    'date': appt.start_datetime.strftime('%Y-%m-%d %H:%M') if appt.start_datetime else '',
                    'state': appt.state,
                    'revenue': appt_rev,
                })

            # 2. Commissions for this staff member in date range
            comm_domain = [
                ('staff_id', '=', staff.id),
                ('date', '>=', date_from),
                ('date', '<=', date_to)
            ]
            commissions = self.env['salon.commission'].sudo().search(comm_domain)
            total_comm = sum(commissions.mapped('commission_amount'))
            paid_comm = sum(commissions.filtered(lambda c: c.state == 'paid').mapped('commission_amount'))
            unpaid_comm = total_comm - paid_comm

            # 3. Tips for this staff member in date range
            tip_domain = [
                ('staff_id', '=', staff.id),
                ('date', '>=', date_from),
                ('date', '<=', date_to)
            ]
            tips = self.env['salon.staff.tip'].sudo().search(tip_domain)
            total_tips = sum(tips.mapped('amount'))
            paid_tips = sum(tips.filtered(lambda t: t.state == 'paid').mapped('amount'))
            unpaid_tips = total_tips - paid_tips

            # 4. Client Reviews & Ratings
            review_domain = [
                ('staff_id', '=', staff.id),
                ('date', '>=', date_from),
                ('date', '<=', date_to)
            ]
            reviews = self.env['salon.review'].sudo().search(review_domain)
            review_count = len(reviews)
            avg_rating = sum(reviews.mapped('rating')) / review_count if review_count > 0 else 0.0

            cancel_rate = (cancel_appts / total_appts * 100.0) if total_appts > 0 else 0.0
            staff_branch_names = list(set(appts.mapped('branch_id.name')))
            branch_name_str = ', '.join(filter(None, staff_branch_names)) if staff_branch_names else 'All Branches'

            staff_performance.append({
                'id': staff.id,
                'name': staff.name,
                'role': staff.job_title or 'Beautician / Specialist',
                'branch_name': branch_name_str,
                'total_appts': total_appts,
                'done_appts': done_appts,
                'cancel_appts': cancel_appts,
                'active_appts': active_appts,
                'cancel_rate': round(cancel_rate, 1),
                'revenue': staff_revenue,
                'total_comm': total_comm,
                'paid_comm': paid_comm,
                'unpaid_comm': unpaid_comm,
                'total_tips': total_tips,
                'paid_tips': paid_tips,
                'unpaid_tips': unpaid_tips,
                'review_count': review_count,
                'avg_rating': round(avg_rating, 1),
                'services_log': services_log,
            })

            grand_total_revenue += staff_revenue
            grand_total_tips += total_tips
            grand_total_commissions += total_comm
            grand_total_done += done_appts
            if review_count > 0:
                total_ratings_sum += sum(reviews.mapped('rating'))
                total_ratings_count += review_count

        grand_avg_rating = round(total_ratings_sum / total_ratings_count, 1) if total_ratings_count > 0 else 0.0
        branch_names = [b.name for b in self.env['salon.branch'].sudo().browse(branch_ids)] if branch_ids else ['All Branches']

        return {
            'doc_ids': docids,
            'doc_model': 'salon.staff.report.wizard',
            'data': data,
            'staff_performance': staff_performance,
            'grand_total_revenue': grand_total_revenue,
            'grand_total_tips': grand_total_tips,
            'grand_total_commissions': grand_total_commissions,
            'grand_total_done': grand_total_done,
            'grand_avg_rating': grand_avg_rating,
            'branch_names_str': ', '.join(branch_names),
            'print_date': datetime.date.today().strftime('%Y-%m-%d'),
        }
